### ISSUE TITLE
[FEATURE] Save as .mp3

### ISSUE THREAD

**Issue by Mr-Foxtrot** [avi12/youtube-downloader#1]
The title basically explains it but an option to save as .mp3 instead of MP4 can be handy and save time.

**Comment by avi12** [comment]
As specified in the [README](https://github.com/avi12/youtube-downloader#:~:text=Specify%20what%20to%20download%20-%20video-only%2C%20audio-only%20or%20video%20%2B%20audio), it is a planned feature
My priority is to first make sure the download manager is working properly, and only then implement the small features

**Comment by avi12** [comment]
A few hours ago, I released version [0.6.0](https://github.com/avi12/youtube-downloader/releases/tag/0.6.0)
As of now, I think I implemented the core features that are the most important, hence now I'm working on diversifying the download types (i.e. video & audio)

**Comment by Mr-Foxtrot** [comment]
Ah I see, accidentally skipped over it when reading the README, my apologies.

**Comment by avi12** [comment]
Seems like I'm having a little [issue](https://stackoverflow.com/q/69003427/8309806)

**Comment by avi12** [comment]
@Mr-Foxtrot I released version [0.7.0](https://github.com/avi12/youtube-downloader/releases/tag/0.7.0) that lets you click on a video in a "Music" category to download it as MP3
