### ISSUE TITLE
[Bug] Can not download 1080pHD

### ISSUE THREAD

**Issue by yemingfeng** [avi12/youtube-downloader#8]
### Describe the bug

Can not download 1080pHD

### How to reproduce

https://www.youtube.com/watch?v=gYpEshVKJxU

### Expected behavior

Can not download 1080pHD

### What browser(s) can you reproduce the issue on?

Chrome

### What OS does it occur on?

macOS

### What's the version you're running?

1.0.5

**Comment by yemingfeng** [comment]
Thank you very much for providing the code, which allows me to download any content freely.

**Comment by avi12** [comment]
Currently I don't maintain this extension as I focus my efforts on [YouTube TIme Manager](https://chromewebstore.google.com/detail/fpoooibdndpjcnoodfionoeakeojdjaj)
Once I'm done with it, I can maintain this one, which will require a complete rewrite from scratch to make it compatible with [Manifest V3](https://developer.chrome.com/docs/extensions/develop/migrate/what-is-mv3)

Though if you'd like to migrate to [MV3](https://developer.chrome.com/docs/extensions/develop/migrate/what-is-mv3), you're more than welcome, but make sure to use [Plasmo](https://github.com/plasmohq/plasmo)
